import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const output = new URL('../verification/', import.meta.url);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1, hasTouch: true });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto('http://127.0.0.1:5178', { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__diorama?.state.frames > 3, { timeout: 60000 });
await page.evaluate(() => window.__diorama.seek(20));
await page.screenshot({ path: new URL('desktop.png', output).pathname.replace(/^\/(\w:)/, '$1') });
const initial = await page.evaluate(() => ({ state: window.__diorama.state, pixels: window.__diorama.pixelStats(), ui: document.body.innerText.trim(), canvas: document.querySelectorAll('canvas').length }));
assert.equal(initial.ui, '', 'No visible UI text');
assert.equal(initial.canvas, 1, 'Only one visible canvas');
assert.ok(initial.pixels.greens > 120, 'Grass renders');
assert.ok(initial.pixels.pinks > 80, 'Sakura trees render');
assert.ok(initial.pixels.dark > 50, 'Model details render');

const getCamera = () => page.evaluate(() => window.__diorama.camera.position.toArray());
const beforeDrag = await getCamera();
await page.mouse.move(690, 535); await page.mouse.down();
await page.mouse.move(1030, 535, { steps: 15 }); await page.mouse.up();
await page.waitForTimeout(500);
assert.notDeepEqual(await getCamera(), beforeDrag, 'Dragging rotates camera');
const zoomBefore = await page.evaluate(() => window.__diorama.camera.zoom);
await page.mouse.wheel(0, -240); await page.waitForTimeout(400);
const zoomAfter = await page.evaluate(() => window.__diorama.camera.zoom);
assert.ok(zoomAfter > zoomBefore, 'Scroll zooms in');
await page.evaluate(() => { window.__diorama.resetView(); window.__diorama.setView(205, 42); });
await page.waitForTimeout(200);
await page.screenshot({ path: new URL('reverse.png', output).pathname.replace(/^\/(\w:)/, '$1') });
const reversePixels = await page.evaluate(() => window.__diorama.pixelStats());
assert.ok(reversePixels.greens > 120 && reversePixels.pinks > 80, 'Reverse view is rendered');
await page.evaluate(() => { window.__diorama.resetView(); window.__diorama.seek(36); });
await page.waitForTimeout(100);
await page.screenshot({ path: new URL('crossing.png', output).pathname.replace(/^\/(\w:)/, '$1') });
const crossing = await page.evaluate(() => window.__diorama.state);
assert.ok(crossing.warning && crossing.gateAngle < .02, 'Crossing barriers down during passage');
await page.evaluate(() => window.__diorama.seek(31));
const positionA = await page.evaluate(() => ({ x: window.__diorama.state.trainX, petals: window.__diorama.scene.getObjectByName('Drifting cherry petals').instanceMatrix.array.slice(0, 16) }));
await page.evaluate(() => window.__diorama.seek(33));
const positionB = await page.evaluate(() => ({ x: window.__diorama.state.trainX, petals: window.__diorama.scene.getObjectByName('Drifting cherry petals').instanceMatrix.array.slice(0, 16) }));
assert.notEqual(positionA.x, positionB.x, 'Train moves');
assert.notDeepEqual(positionA.petals, positionB.petals, 'Petals move');

await page.setViewportSize({ width: 390, height: 844 });
await page.evaluate(() => { window.__diorama.resetView(); window.__diorama.seek(20); });
await page.waitForTimeout(250);
await page.screenshot({ path: new URL('mobile.png', output).pathname.replace(/^\/(\w:)/, '$1') });
const mobile = await page.evaluate(() => {
  const d = window.__diorama, corners = [];
  for (const x of [-12.04, 12.04]) for (const z of [-12.04, 12.04]) {
    const point = d.camera.position.clone().set(x, -1.38, z).project(d.camera);
    corners.push({ x: point.x, y: point.y });
  }
  return { corners, pixels: d.pixelStats(), canvasWidth: document.querySelector('canvas').clientWidth, viewportWidth: innerWidth };
});
assert.ok(mobile.corners.every(p => Math.abs(p.x) < 1 && Math.abs(p.y) < 1), 'Complete model base fits mobile');
assert.ok(mobile.pixels.greens > 70 && mobile.pixels.pinks > 30, 'Mobile canvas is nonblank');
assert.equal(mobile.canvasWidth, mobile.viewportWidth, 'No horizontal overflow');
const mobileCamera = await getCamera();
const cdp = await page.context().newCDPSession(page);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 180, y: 410, id: 0 }] });
for (let i = 1; i <= 10; i++) await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 180 + i * 10, y: 410, id: 0 }] });
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
await page.waitForTimeout(300);
assert.notDeepEqual(await getCamera(), mobileCamera, 'Touch dragging rotates camera');
const touchZoomBefore = await page.evaluate(() => window.__diorama.camera.zoom);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 150, y: 410, id: 0 }, { x: 220, y: 410, id: 1 }] });
for (let i = 1; i <= 8; i++) await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 150 - i * 5, y: 410, id: 0 }, { x: 220 + i * 5, y: 410, id: 1 }] });
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
await page.waitForTimeout(300);
const touchZoomAfter = await page.evaluate(() => window.__diorama.camera.zoom);
assert.ok(touchZoomAfter > touchZoomBefore, 'Pinch zoom changes camera zoom');
await page.setViewportSize({ width: 1440, height: 1080 });
await page.evaluate(() => { window.__diorama.resetView(); window.__diorama.setView(24, 32, 1.75); window.__diorama.seek(20); });
await page.waitForTimeout(200);
await page.screenshot({ path: new URL('station-detail.png', output).pathname.replace(/^\/(\w:)/, '$1') });
assert.deepEqual(errors, [], 'No browser errors');
const report = { initial, reversePixels, crossing, mobile, zoomBefore, zoomAfter, touchZoomBefore, touchZoomAfter, errors, checks: ['desktop-render', 'mobile-render', 'reverse-render', 'no-ui', 'drag-orbit', 'wheel-zoom', 'touch-orbit', 'pinch-zoom', 'gate-interlock', 'train-motion', 'petal-motion', 'mobile-framing'] };
await writeFile(new URL('browser-report.json', output), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
await browser.close();
